<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AccessResource\Entity\AccessLog[] $logs
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->headLink()->appendStylesheet($this->assetUrl('css/table-access-resource.css', 'AccessResource'));
$this->htmlElement('body')->appendAttribute('class', 'sites browse');
?>

<?= $this->pageTitle($translate('Access logs')) ?>

<?php if (count($logs)): ?>
    <div class="browse-controls">
        <?= $this->pagination() ?>
    </div>
    <?php $this->trigger('view.browse.before'); ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <th><?= $escape($translate('User')) ?></th>
            <th><?= $escape($translate('Action')) ?></th>
            <th><?= $escape($translate('Record Id')) ?></th>
            <th><?= $escape($translate('Type')) ?></th>
            <th><?= $escape($translate('Date')) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($logs as $log): ?>
            <?php
                if ($user = $log->getUser()):
                    $userText = $this->hyperlink(
                        $user->getName(),
                        $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $user->getId()])
                    );
                else:
                    $userText = $translate('[no user]');
                endif;
            ?>
            <tr>
                <td><?= $userText ?></td>
                <td><?= $log->getAction() ?></td>
                <td><?= $log->getRecordId() ?></td>
                <td><?= $log->getType() ?></td>
                <td><?= $log->getDate()->format('Y-m-d H:i:s') ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php $this->trigger('view.browse.after'); ?>

<?php else: ?>

    <p><?= $escape($translate('No access records yet.')); ?> <a href="<?= $this->url(null, [], true); ?>"><?= $escape($translate('Refresh page')); ?></a></p>

<?php endif; ?>
