<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 * @var string $resourceType
 */

use \Access\Api\Representation\AccessStatusRepresentation;
use \Common\Form\Element\OptionalRadio;

$plugins = $this->getHelperPluginManager();
$setting = $plugins->get('setting');

$accessLevels = $setting('access_property_levels', AccessStatusRepresentation::LEVELS);
$valueOptions = ['' => 'All'] + $accessLevels;
unset($valueOptions['protected']);

$accessElement = (new OptionalRadio('access'))
    ->setLabel('Access')
    ->setLabelAttributes(['class' => 'type-radio'])
    ->setValueOptions($valueOptions)
    ->setValue($query['access'] ?? '');
?>

<?= $this->formRow($accessElement) ?>
