<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 * @var string $resourceType
 */

use \Access\Api\Representation\AccessStatusRepresentation;
use \Common\Form\Element\OptionalMultiCheckbox;

$plugins = $this->getHelperPluginManager();
$setting = $plugins->get('setting');

$accessLevels = $setting('access_property_levels', AccessStatusRepresentation::LEVELS);
$fullAccess = (bool) $setting('access_full');
if (!$fullAccess) {
    unset($accessLevels['protected']);
}

// Default to all levels selected when no query is set.
$queryAccess = $query['access'] ?? [];
if (!is_array($queryAccess)) {
    $queryAccess = $queryAccess ? [$queryAccess] : [];
}

$accessElement = (new OptionalMultiCheckbox('access'))
    ->setLabel('Access')
    ->setLabelAttributes(['class' => 'type-checkbox'])
    ->setValueOptions($accessLevels)
    ->setValue($queryAccess);
?>

<?= $this->formRow($accessElement) ?>
