<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Entity\User|null $user
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $requestables
 * @var \AccessResource\Form\Site\AccessRequestForm $form
 * @var string $requestType
 */

// Don't display the form if there is nothing to request.
if (!count($requestables)) return;

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$hasGuest = $plugins->has('guestWidget');

$this->headLink()->appendStylesheet($assetUrl('css/access-request.css', 'AccessResource'));
$this->headScript()->appendFile($assetUrl('js/access-request.js', 'AccessResource'), 'text/javascript', ['defer' => 'defer']);

$formSubmitUrl = $this->url('site/access-request', [], true);
?>

<button type="button" class="request-access-resource"><?= $translate('Request access') ?></button>

<dialog class="access-request-form" data-uri="<?= $formSubmitUrl ?>">
    <div class="form-wrapper">
        <div class="form-block">
            <div class="block-title">
                <h3><?= $translate('Request access') ?></h3>
                <button type="button" class="block-close o-icon-close">
                    <span class="screen-reader-text"><?= $translate('Close') ?></span>
                </button>
            </div>
            <div class="block-body">

                <?php if ($user): ?>

                    <?= $this->form($form) ?>

                <?php elseif ($hasGuest): ?>

                    <div>
                        <?php
                        if ($this->setting('guest_open') === 'close'):
                            echo sprintf(
                                $translate('To request access please %1$slogin%2$s or contact the publisher!'),
                                sprintf('<a href="%s">' , $url('site/guest/anonymous', ['action' => 'login'], true)),
                                '</a>'
                            );
                        else:
                            echo sprintf(
                                $translate('To request access please %1$slogin%3$s or %2$sregister%3$s!'),
                                sprintf('<a href="%s">' , $url('site/guest/anonymous', ['action' => 'login'], true)),
                                sprintf('<a href="%s">' , $url('site/guest/anonymous', ['action' => 'register'], true)),
                                '</a>'
                            );
                        endif;
                        ?>
                    </div>

                <?php else: ?>

                    <div>
                        <?= $translate('To request access please contact the publisher!') ?>
                    </div>

                <?php endif; ?>

            </div>
        </div>
    </div>
</dialog>
