<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Access\Api\Representation\AccessStatusRepresentation|null $accessStatus
 */

// Display the access status of a resource.

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');

if ($accessStatus) {
    $level = $accessStatus->displayLevel();
    $embargo = $accessStatus->displayEmbargo('medium');
} else {
    $level = $escape($translate('Free'));
    $embargo = null;
}
?>

<div class="meta-group access-status">
    <h4><?= $translate('Access status') ?></h4>
    <div class="value"><?= $level ?></div>
    <?php if ($embargo): ?>
    <div class="value"><?= $embargo ?></div>
    <?php endif; ?>
</div>
