<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \AccessResource\Api\Representation\AccessResourceRepresentation[] $accesses
 * @var \Omeka\Api\Representation\AbstractResourceRepresentation $resource
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()
    ->appendStylesheet($this->assetUrl('css/access-resource-admin.css', 'AccessResource'));
$this->headScript()
    ->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'))
    ->appendFile($this->assetUrl('js/user-selector.js', 'AccessResource'))
    ->appendFile($this->assetUrl('js/access-resource-admin.js', 'AccessResource'));
?>

<div class="access-resource">

<?php if (empty($accesses)): ?>
    <div class="no-resources">
        <p><?php echo $translate('There are no access for this resource.'); ?></p>
    </div>
<?php else: ?>
<?php
    // $resourceName = $resource->getControllerName();
    $updateRight = $this->userIsAllowed(\AccessResource\Entity\AccessResource::class, 'update');
?>
    <ul>
    <?php foreach ($accesses as $access): ?>
        <?php
            $user = $access->user();
            $userText = $user ? $this->hyperlink($user->name(), $user->adminUrl()) : '';
        ?>

        <li class="value tag">id: <?php echo $access->id(); ?>
            <span><?php echo sprintf($translate('user: %s'), $userText); ?></span>
            <?php if ($updateRight): ?>
                <span class="single actions"><a href="#"
                    class="status-toggle-accessresource o-icon-<?php echo $access->enabled() ? 'approved' : 'private' ?>"
                    data-status-toggle-url="<?php echo $this->url("admin/access-resource/id", [
                        'id' => $access->id(),
                        'action' => "toggle" ]) ?>"
                    data-status="<?php echo $access->enabled() ? 'approved' : 'private' ?>"
                    aria-label="<?php echo $escape($translate('Toggle access')); ?>"
                    title="<?php echo $escape($translate('Toggle access')); ?>"></a></span>
                <span class="single actions"><a href="#"
                    class="o-icon-delete"
                    data-status-toggle-url="<?php echo $this->url("admin/access-resource/id", [
                            'id' => $access->id(),
                            'action' => "delete" ])  ?>"
                    data-status="<?php  ?>"
                    aria-label="<?php echo $escape($translate('Remove access')); ?>"
                    title="<?php echo $escape($translate('Remove access')); ?>"></a></span>

            <?php else: ?>
            <span class="no-action o-icon-<?php echo $access->enabled() ?: 'undefined'; ?>"></span>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>

    <form action="<?php echo $this->url("admin/access-resource/default", [
        'controller' => 'access',
        'action' => 'edit',
    ]); ?>" method="post">
        <div class="resource-values field">
            <div class="field-meta">
                <div class="field-label"><?php echo $translate('New access'); ?></div>
            </div>
            <div class="inputs">
                <?php ?>
                <input type="hidden" name="csrf" value="<?php echo (new \Zend\Form\Element\Csrf('csrf'))->getValue(); ?>">
                <input type="hidden" name="resource_id" value="<?php echo $resource ? $resource->id() : ''; ?>">
                <input type="hidden" name="user_id" value="<?php echo $user ? $user->id() : ''; ?>">
                <input type="hidden" name="enabled" value="<?php echo 1; ?>">
                <input type="hidden" name="temporal" value="<?php echo 0; ?>">
                <input type="hidden" name="startDate" value="<?php echo (new \DateTime())->format('Y-m-d H:i'); ?>">
                <input type="hidden" name="endDate" value="<?php echo (new \DateTime())->format('Y-m-d H:i'); ?>">
                <div class="selected-user">
                    <?php
                    if ($user):
                        echo $this->hyperlink($user->name(), $this->url('admin/id', ['controller' => 'user', 'id' => $user->id()], true), ['target' => '_blank']);
                    endif;
                    ?>
                </div>
                <button id="user-selector-button"><?php echo $translate('Select user'); ?></button>
                <?php echo $this->userSelector($translate('Click on a user to select it.'), false); ?>
            </div>
        </div>
        <input type="submit" value="<?php echo $escape($translate('Add access')); ?>">
    </form>
</div>

<script>
    $(document).ready(function() {
        var value = $('form .value-resource');
        var valueObj = <?php echo $resource ? json_encode($resource->valueRepresentation()) : '{}' ?>;
        var namePrefix = value.data('name-prefix');
        $(document).trigger('o:prepare-value', ['resource', value, valueObj, namePrefix]);
    });
</script>
