<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AccessResource\Api\Representation\AccessResourceRepresentation[] $accesses
 * @var \AccessResource\Api\Representation\AccessRequestRepresentation[] $requests
 * @var \Omeka\Api\Representation\AbstractResourceRepresentation $resource
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');

$this->headLink()
    ->appendStylesheet($this->assetUrl('css/access-resource-admin.css', 'AccessResource'));
$this->headScript()
    ->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($this->assetUrl('js/user-selector.js', 'AccessResource'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($this->assetUrl('js/access-resource-admin.js', 'AccessResource'), 'text/javascript', ['defer' => 'defer']);
?>

<div class="access-resource access-request">

    <?php // Manage user requests. ?>

    <div class="access-requests">
        <h4><?= $translate('User requests') ?></h4>

    <?php if (empty($requests)): ?>

    <div class="no-resources">
        <p><?= $translate('There are no requests for this resource.') ?></p>
    </div>

    <?php else: ?>

    <?php
    // TODO Add a button to clean all access to public resources (and mutiple toggle/deletion anyway).

    // $resourceName = $resource->getControllerName();
    $updateRight = $this->userIsAllowed(\AccessResource\Entity\AccessRequest::class, 'update');
    ?>
    <ul>
    <?php foreach ($requests as $request): ?>
        <?php
            $user = $request->user();
            $userText = $user ? $hyperlink($user->name(), $user->adminUrl()) : '';
            $status = $request->status();
        ?>

        <li class="value tag" data-id="<?= $request->id() ?>">
            <span><?= sprintf($translate('user: %s'), $userText) ?></span>
            <?php if ($updateRight): ?>
            <span class="single actions"><a href="<?= $urlHelper('admin/access-resource/id', ['controller' => 'request', 'id' => $request->id(), 'action' => 'edit']) ?>"
                class="o-icon-edit"
                aria-label="<?= $escape($translate('Edit')) ?>"
                title="<?= $escape($translate('Edit')) ?>"></a></span>
            <span class="single actions"><a href="#"
                class="status-toggle-access-resource o-icon-<?= $status ?>"
                data-status-toggle-url="<?= $this->url("admin/access-resource/id", ['controller' => 'request', 'id' => $request->id(), 'action' => "toggle" ]) ?>"
                data-status="<?= $status ?>"
                aria-label="<?= $escape($translate('Toggle request')) ?>"
                title="<?= $escape($translate('Toggle request')) ?>"></a></span>
            <span class="single actions"><a href="#"
                class="o-icon-delete"
                data-status-toggle-url="<?= $this->url('admin/access-resource/id', ['controller' => 'request', 'id' => $request->id(), 'action' => 'delete']) ?>"
                aria-label="<?= $escape($translate('Remove request')) ?>"
                title="<?= $escape($translate('Remove request')) ?>"></a></span>
            <?php else: ?>
            <span class="no-action o-icon-<?= $status ?>"></span>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>

    <?php endif; ?>

    </div>

    <?php // Manage resource access. ?>

    <div class="access-resources">
        <h4><?= $translate('Accesses') ?></h4>

    <?php if (empty($accesses)): ?>

    <div class="no-resources">
        <p><?= $translate('There are no access for this resource.'); ?></p>
    </div>

    <?php else: ?>

    <?php
    // TODO Add a button to clean all access to public resources (and mutiple toggle/deletion anyway).

    // $resourceName = $resource->getControllerName();
    $updateRight = $this->userIsAllowed(\AccessResource\Entity\AccessResource::class, 'update');
    ?>
    <ul>
    <?php foreach ($accesses as $access): ?>
        <?php
            $user = $access->user();
            $userText = $user ? $hyperlink($user->name(), $user->adminUrl()) : '';
        ?>

        <li class="value tag" data-id="<?= $access->id() ?>">
            <span><?= sprintf($translate('user: %s'), $userText) ?></span>
            <?php if ($updateRight): ?>
            <span class="single actions"><a href="<?= $urlHelper('admin/access-resource/id', ['id' => $access->id(), 'action' => 'edit']) ?>"
                class="o-icon-edit"
                aria-label="<?= $escape($translate('Edit')) ?>"
                title="<?= $escape($translate('Edit')) ?>"></a></span>
            <span class="single actions"><a href="#"
                class="status-toggle-access-resource o-icon-<?= $access->enabled() ? 'approved' : 'private' ?>"
                data-status-toggle-url="<?= $this->url("admin/access-resource/id", ['id' => $access->id(), 'action' => "toggle" ]) ?>"
                data-status="<?= $access->enabled() ? 'approved' : 'private' ?>"
                aria-label="<?= $escape($translate('Toggle access')) ?>"
                title="<?= $escape($translate('Toggle access')) ?>"></a></span>
            <span class="single actions"><a href="#"
                class="o-icon-delete"
                data-status-toggle-url="<?= $this->url('admin/access-resource/id', ['id' => $access->id(), 'action' => 'delete']) ?>"
                aria-label="<?= $escape($translate('Remove access')) ?>"
                title="<?= $escape($translate('Remove access')) ?>"></a></span>
            <?php else: ?>
            <span class="no-action o-icon-<?= $access->enabled() ?: 'undefined' ?>"></span>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>

    <?php endif; ?>

    </div>

    <?php // Quick form to add access. ?>

    <div>
        <h4><?= $translate('Add an access') ?></h4>

     <?php if ($resource->isPublic()): ?>

    <div class="no-resources">
        <p><?= $translate('This resource is public: no access is needed to view it.'); ?></p>
    </div>

    <?php elseif (!$resource->value('curation:reserved')): ?>

    <div class="no-resources">
        <p><?= $translate('This resource is private and not marked reservable: no access is possible.'); ?></p>
    </div>

    <?php // Manage access to private resource when marked reservable. ?>
    <?php else: ?>

    <form action="<?= $this->url("admin/access-resource/default", [
        'controller' => 'access',
        'action' => 'edit',
    ]) ?>" method="post">
        <div class="resource-values field">
            <div class="field-meta">
                <div class="field-label"><?= $translate('New access') ?></div>
            </div>
            <div class="inputs">
                <input type="hidden" name="csrf" value="<?= (new \Laminas\Form\Element\Csrf('csrf'))->getValue() ?>">
                <input type="hidden" name="resource_id" value="<?= $resource ? $resource->id() : '' ?>">
                <input type="hidden" name="user_id" value="">
                <input type="hidden" name="enabled" value="<?= 1 ?>">
                <input type="hidden" name="temporal" value="<?= 0 ?>">
                <input type="hidden" name="startDate" value="<?= (new \DateTime())->format('Y-m-d H:i') ?>">
                <input type="hidden" name="endDate" value="<?= (new \DateTime())->format('Y-m-d H:i') ?>">
                <div class="selected-user">
                </div>
                <button id="user-selector-button"><?= $translate('Select user') ?></button>
                <?= $this->userSelector($translate('Click on a user to select it.'), false) ?>
            </div>
        </div>
        <input type="submit" value="<?= $escape($translate('Add access')) ?>">
    </form>

    <?php // TODO Move to js file. ?>
    <script>
        $(document).ready(function() {
            var value = $('form .value-resource');
            var valueObj = <?= $resource ? json_encode($resource->valueRepresentation()) : '{}' ?>;
            var namePrefix = value.data('name-prefix');
            $(document).trigger('o:prepare-value', ['resource', value, valueObj, namePrefix]);
        });
    </script>

    <?php endif; ?>

    </div>

</div>
