<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $linkTitle
 * @var string $values
 * @var \Access\Api\Representation\AccessRequestRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$accessRequest = $resource;
?>

<div class="resource-details" data-resource-values="<?= $escape($values) ?>">

    <?php if ($linkTitle): ?>
    <h3 class="o-title"><?= $resource->link($resource->displayTitle()) ?></h3>
    <?php else: ?>
    <h3 class="o-title"><?= $escape($resource->displayTitle()) ?></h3>
    <?php endif; ?>
    <div class="o-description"><?= $escape($resource->displayDescription()) ?></div>

    <div class="meta-group">
        <h4><?= $escape($translate('Requester')) ?></h4>
        <div class="value"><?= $accessRequest->displayRequester() ?></div>
    </div>

    <div class="meta-group">
        <h4><?= $escape($translate('Resources')) ?></h4>
        <div class="value"><?= $accessRequest->displayResources() ?></div>
    </div>

    <div class="meta-group">
        <h4><?= $escape($translate('Recursive')) ?></h4>
        <div class="value"><?= $accessRequest->displayRecursive() ?></div>
    </div>

    <div class="meta-group">
        <h4><?= $escape($translate('Status')) ?></h4>
        <div class="value"><?= $accessRequest->displayStatus() ?></div>
    </div>

    <?php if ($temporal = $accessRequest->displayTemporal()): ?>
    <div class="meta-group">
        <h4><?= $escape($translate('Dates')) ?></h4>
        <div class="value"><?= $temporal ?></div>
    </div>
    <?php endif; ?>

    <?php if ($name = $accessRequest->name()): ?>
    <div class="meta-group">
        <h4><?= $escape($translate('Name')) ?></h4>
        <div class="value"><?= $escape($name) ?></div>
    </div>
    <?php endif; ?>

    <?php if ($message = $accessRequest->message()): ?>
    <div class="meta-group">
        <h4><?= $escape($translate('Message')) ?></h4>
        <div class="value"><?= $escape($message) ?></div>
    </div>
    <?php endif; ?>

    <?php if ($fields = $accessRequest->fields()): ?>
    <div class="meta-group">
        <h4><?= $escape($translate('Fields')) ?></h4>
        <div class="value"><?= json_encode($fields, 448) ?></div>
    </div>
    <?php endif; ?>

    <div class="meta-group">
        <h4><?= $escape($translate('Created')) ?></h4>
        <div class="value"><?=  $i18n->dateFormat($accessRequest->created()) ?></div>
    </div>

    <?php if ($modified = $accessRequest->modified()): ?>
    <div class="meta-group">
        <h4><?= $escape($translate('Modified')) ?></h4>
        <div class="value"><?=  $i18n->dateFormat($modified) ?></div>
    </div>
    <?php endif; ?>

    <?php $this->trigger('view.details', ['entity' => $resource]) ?>
</div>
