<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var bool $isAccessRequestable
 *
 * @see \Access\View\Helper\AccessRequest
 */

// Display the access request form of a resource.

// By default, this check is done by the view helper too.
// if (!$isAccessRequestable) return;

echo $this->accessRequest($resource);
