<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var \AccessResource\Form\AccessRequestForm $form
 * @var bool $visitorHasIdentity
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$assetUrl = $plugins->get('assetUrl');

$this->headLink()->appendStylesheet($assetUrl('css/helper-request-resource-access-form.css', 'AccessResource'));
$this->headScript()->appendFile($assetUrl('js/helper-request-resource-access-form.js', 'AccessResource'), 'text/javascript', ['defer' => 'defer']);

$formSubmitUrl = $this->url('site/access-resource-request', [], true);
?>

<?= $hyperlink(
    $translate('Request resource access'),
    'javascript: void(0)',
    ['class' => 'button request-access-resource']
) ?>

<div class="access-resource-request-form" data-uri="<?= $formSubmitUrl ?>">
    <div class="form-wrapper">
        <div class="form-block">
            <div class="block-title">
                <h3><?= $translate('Request Access') ?></h3>
                <a href="javascript: void(0)" class="block-close o-icon-close">
                    <span class="screen-reader-text"><?= $translate('Close') ?></span>
                </a>
            </div>
            <div class="block-body">
                <?php if ($visitorHasIdentity): ?>

                    <?= $this->form()->openTag($form) ?>
                    <?php foreach ($resources as $resource): ?>
                <div>
                    <label>
                        <input type="checkbox" name="resources[]" value="<?= $resource->id() ?>">
                        <?= $resource->linkPretty() ?>
                    </label>
                </div>
                    <?php endforeach; ?>
                    <?= $this->formHidden($form->get('csrf')) ?>
                    <br/>
                    <?= $this->formRow($form->get('access_request_submit')->get('submit')) ?>
                    <?= $this->form()->closeTag() ?>

                <?php else: ?>

                <div>
                    <?php
                    if ($this->setting('guest_open') === 'close'):
                        echo sprintf(
                            $translate('To request access please %s or contact the publisher!'),
                            $hyperlink($translate('Login'), $this->url('site/guest/anonymous', ['action' => 'login'], true))
                        );
                    else:
                        echo sprintf(
                            $translate('To request access please %s or %s!'),
                            $hyperlink($translate('Register'), $this->url('site/guest/anonymous', ['action' => 'register'], true)),
                            $hyperlink($translate('Login'), $this->url('site/guest/anonymous', ['action' => 'login'], true))
                        );
                    endif;
                ?>
                </div>

                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
