<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AccessResource\Api\Representation\AccessRequestRepresentation[] $accessRequests
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$sortHeadings = [
    [
        'label' => $translate('User'),
        'value' => 'user',
    ],
    [
        'label' => $translate('Resource'),
        'value' => 'resource',
    ],
    [
        'label' => $translate('Status'),
        'value' => 'status',
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created',
    ],
    [
        'label' => $translate('Modified'),
        'value' => 'modified',
    ],
];

$this->headLink()->appendStylesheet($this->assetUrl('css/access-resource-admin.css', 'AccessResource'));
$this->htmlElement('body')->appendAttribute('class', 'access-requests browse');
?>

<?= $this->pageTitle($translate('Access requests')) ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed(\AccessResource\Entity\AccessRequest::class, 'create')): ?>
        <?= $this->hyperlink($translate('Add new request'), $url('admin/access-request/default', ['action' => 'add']), ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<?php if (count($accessRequests)): ?>
    <div class="browse-controls">
        <?= $this->pagination() ?>
        <?= $this->sortSelector($sortHeadings) ?>
    </div>
    <?php $this->trigger('view.browse.before'); ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <th><?= $escape($translate('User')) ?></th>
            <th><?= $escape($translate('Resource')) ?></th>
            <th><?= $escape($translate('Status')) ?></th>
            <th>&nbsp;</th>
            <th><?= $escape($translate('Created')) ?></th>
            <th><?= $escape($translate('Modified')) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($accessRequests as $accessRequest): ?>
            <?php
                if ($user = $accessRequest->user()):
                    $userText = $this->hyperlink($user->name(), $user->adminUrl());
                else:
                    $userText = $translate('[no user]');
                endif;

                $resourceType = '';
                $resourceText = '';
                if ($requestedResource = $accessRequest->resource()):
                    $resourceType = $requestedResource->resourceName();
                    $resourceText = $requestedResource->linkPretty();
                endif;
                ?>
            <tr>
                <td><?= $userText; ?></td>
                <td class="resource <?= $resourceType; ?>"><?= $resourceText ?></td>
                <td><?= $translate($accessRequest->statusLabel()) ?></td>

                <td>
                    <ul class="actions">
                        <?php if ($accessRequest->userIsAllowed('update')): ?>
                        <li>
                            <?= $this->hyperlink('', $accessRequest->url('edit'), [
                                'class' => 'o-icon-edit',
                                'title' => $translate('Edit'),
                            ]) ?>
                        </li>
                        <?php endif; ?>
                        <?php if ($accessRequest->userIsAllowed('delete')): ?>
                        <li>
                            <?= $this->hyperlink('', '#', [
                                'data-sidebar-selector' => '#sidebar',
                                'data-sidebar-content-url' => $accessRequest->url('delete-confirm'),
                                'class' => 'o-icon-delete sidebar-content',
                                'title' => $translate('Delete'),
                            ]) ?>
                        </li>
                        <?php endif; ?>
                    </ul>
                </td>

                <td><?= $i18n->dateFormat($accessRequest, 'medium', 'medium') ?></td>
                <td><?= $accessRequest->modified() ? $i18n->dateFormat($accessRequest->modified(), 'medium', 'medium') : '' ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php $this->trigger('view.browse.after'); ?>
    <div class="browse-controls">
        <?= $this->pagination() ?>
    </div>

    <div id="sidebar" class="sidebar">
        <?= $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]) ?>
        <div class="sidebar-content"></div>
    </div>
    <div id="sidebar-delete-selected" class="sidebar">
        <?= $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]) ?>
        <div class="sidebar-content">
            <div id="sidebar-confirm">
                <h3><?= $translate('Delete records') ?></h3>
                <p><?= $translate('Are you sure you would like to delete the selected records?') ?></p>
                <p class="error"><?= sprintf(
                        $translate('%s: this action will permanently delete %s records and cannot be undone.'),
                        sprintf('<strong>%s</strong>', $translate('Warning')),
                        '<strong><span id="delete-selected-count"></span></strong>'
                    ) ?></p>
                <?= 'formDeleteSelected' /*$this->form($this->formDeleteSelected)*/ ?>
            </div>
        </div>
    </div>
    <div id="sidebar-delete-all" class="sidebar">
        <?= $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]) ?>
        <div class="sidebar-content">
            <div id="sidebar-confirm">
                <h3><?= $translate('Delete records') ?></h3>
                <p><?= $translate('Are you sure you would like to delete all records on all pages of this result?') ?></p>
                <p class="error"><?= sprintf(
                        $translate('%s: this action will permanently delete %s records and cannot be undone.'),
                        sprintf('<strong>%s</strong>', $translate('Warning')),
                        sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
                    ) ?></p>
                <label><input type="checkbox" name="confirm-delete-all-check"> <?= $translate('Are you sure?') ?></label>
                <?= 'formDeleteAll' /*$this->form($this->formDeleteAll)*/ ?>
            </div>
        </div>
    </div>

    <script>
        // Complete the batch delete form after confirmation.
        $('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
            var confirmForm = $(this);
            if ('confirm-delete-all' === this.id) {
                confirmForm.append($('.batch-query').clone());
            } else {
                $('#batch-form').find('input[name="resource_ids[]"]:checked').each(function() {
                    confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
                });
            }
        });
        $('.delete-all').on('click', function(e) {
            Omeka.closeSidebar($('#sidebar-delete-selected'));
        });
        $('.delete-selected').on('click', function(e) {
            Omeka.closeSidebar($('#sidebar-delete-all'));
            var inputs = $('input[name="resource_ids[]"]');
            $('#delete-selected-count').text(inputs.filter(':checked').length);
        });
        $('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
            $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
        });
    </script>

<?php else: ?>
    <p><?= $escape($translate('No access records yet.')); ?> <a href="<?= $url(null, [], true); ?>"><?= $escape($translate('Refresh page')) ?></a></p>
<?php endif; ?>
