<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\DataType\Resource\AbstractResource $dataType
 * @var \AccessResource\Api\Representation\AccessRequestRepresentation $accessRequest
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $requestedResource
 * @var \AccessResource\Form\Admin\AccessResourceForm $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$urlHelper = $plugins->get('url');
$hyperlink = $plugins->get('hyperlink');
$assetUrl = $plugins->get('assetUrl');

$this->headScript()
    // The sidebar partial load resource-selector.js.
    ->appendFile($assetUrl('js/user-selector.js', 'AccessResource'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/access-resource-admin.js', 'AccessResource'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'access-request edit items');

$deleteButton = ($accessRequest && $accessRequest->userIsAllowed('delete'))
    ? '<a href="javascript: void(0)" class="delete button">' . $translate('Delete') . '</a>'
    : null;

$mediaContentUrlOptions = ['query' => []];
if ($requestedResource && $requestedResource instanceof \Omeka\Api\Representation\ItemRepresentation):
    $mediaContentUrlOptions['query']['item_id'] = $requestedResource->id();
endif;

$user = $accessRequest ? $accessRequest->user() : null;
?>

<script>
var accessObject = <?= $requestedResource ? json_encode($requestedResource->valueRepresentation()) : 'null' ?>;
</script>

<?php
    if ($accessRequest):
        echo $this->pageTitle($accessRequest->displayTitle(), 1, $translate('Access requests'), $translate('Edit'));
    else:
        echo $this->pageTitle($translate('New access request'), 1, $translate('Access requests'), $translate('Add'));
    endif;
?>
<div id="page-actions">
    <?php
        echo $deleteButton;
        echo $hyperlink($translate('Cancel'), $urlHelper('admin/access-request'), ['class' => 'button']);
    ?>
</div>

<?php $this->trigger('view.edit.before'); ?>
<?= $this->form()->openTag($form) ?>
    <?php // Use the same template than the resource form to keep the css and simpler js. ?>
    <div class="resource-values field">
        <div class="field-meta">
            <div class="field-label"><?= $translate('Resource') ?></div>
        </div>
        <div class="inputs">
            <div class="values">
                <div class="value value-resource resource selecting-resource" data-data-type="resource" data-data-type-label="resource" data-data-type-icon="resource" data-name-prefix="resource" role="group">
                    <div class="input-body">
                        <span class="default"><?= $translate('No resource selected') ?></span>
                        <p class="selected-resource">
                            <span class="o-title"></span>
                            <input type="hidden" class="value to-require" name="resource_id" value="<?= $requestedResource ? $requestedResource->id() : '' ?>">
                        </p>
                        <?php
                            echo $hyperlink($translate('Item'), '#item-resource-select', [
                                'class' => 'o-icon-items button resource-select',
                                'data-sidebar-content-url' => $urlHelper('admin/default', ['controller' => 'item', 'action' => 'sidebar-select'], false),
                            ]);

                            echo $hyperlink($translate('Item set'), '#itemset-resource-select', [
                                'class' => 'o-icon-item-sets button resource-select',
                                'data-sidebar-content-url' => $urlHelper('admin/default', ['controller' => 'item-set', 'action' => 'sidebar-select'], false),
                            ]);

                            echo $hyperlink($translate('Media'), '#media-resource-select', [
                                'class' => 'o-icon-media button resource-select',
                                'data-sidebar-content-url' => $urlHelper('admin/default', ['controller' => 'media', 'action' => 'sidebar-select'], $mediaContentUrlOptions, false),
                            ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="resource-values field">
        <div class="field-meta">
            <div class="field-label"><?= $translate('User') ?></div>
        </div>
        <div class="inputs">
            <input type="hidden" name="user_id" value="<?= $user ? $user->id() : '' ?>">
            <div class="selected-user">
                <?php
                    if ($user):
                        echo $hyperlink($user->name(), $user->adminUrl(), ['target' => '_blank']);
                    endif;
                ?>
            </div>
            <button id="user-selector-button"><?= $user ? $translate('Change user') : $translate('Select user') ?></button>
            <?= $this->userSelector($translate('Click on a user to select it.'), false) ?>
        </div>
    </div>

<?php
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
?>

<?= ($accessRequest) ? $this->deleteConfirm($accessRequest, 'accessRequest') : '' ?>
<?= $this->partial('common/resource-select-sidebar') ?>

<?php $this->trigger('view.edit.after'); ?>
