<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $values
 * @var string $linkTitle
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');

/** @var \AccessResource\Api\Representation\AccessRequestRepresentation $accessRequest */
$accessRequest = $resource;

if ($user = $accessRequest->user()):
    $userText = $this->hyperlink($user->name(), $user->adminUrl(), ['target' => '_blank']);
else:
    $userText = $translate('[no user]');
endif;
?>

<div class="resource-details" data-resource-values="<?= $escape($values) ?>">

    <?php if ($linkTitle): ?>
    <h3 class="o-title"><?= $resource->link($resource->displayTitle()) ?></h3>
    <?php else: ?>
    <h3 class="o-title"><?= $escape($resource->displayTitle()) ?></h3>
    <?php endif; ?>
    <div class="o-description"><?= $escape($resource->displayDescription()) ?></div>

    <?php // echo $this->thumbnail($requestedResource, 'square'); ?>

    <div class="meta-group">
        <h4><?= $escape($translate('User')) ?></h4>
        <div class="value"><?= $userText ?></div>
    </div>

    <div class="meta-group">
        <h4><?= $escape($translate('Resource')) ?></h4>
        <div class="value"><?= $accessRequest->resource()->linkPretty() ?></div>
    </div>

    <div class="meta-group">
        <h4><?= $escape($translate('Status')) ?></h4>
        <div class="value"><?= $translate($resource->statusLabel()) ?></div>
    </div>

    <?php $this->trigger('view.details', ['entity' => $resource]) ?>
</div>
