<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \AccessResource\Api\Representation\AccessResourceRepresentation[] $accessResources
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$urlHelper = $this->plugin('url');

$sortHeadings = [
    [
        'label' => $translate('User'),
        'value' => 'user'
    ],
    [
        'label' => $translate('Resource'),
        'value' => 'resource'
    ],
    [
        'label' => $translate('Enabled'),
        'value' => 'enabled'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
    [
        'label' => $translate('Modified'),
        'value' => 'modified'
    ],
    [
        'label' => $translate('Token'),
        'value' => 'token'
    ],
    [
        'label' => $translate('Start date'),
        'value' => 'startDate'
    ],
    [
        'label' => $translate('End date'),
        'value' => 'endDate'
    ]
];

$this->headLink()->appendStylesheet($this->assetUrl('css/access-resource-admin.css', 'AccessResource'));
$this->htmlElement('body')->appendAttribute('class', 'access-resources browse');
?>

<?= $this->pageTitle($translate('Access resources')) ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed(\AccessResource\Entity\AccessResource::class, 'create')): ?>
        <?= $this->hyperlink($translate('Add new access'), $urlHelper('admin/access-resource/default', ['controller' => 'access', 'action' => 'add']), ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<?php if (count($accessResources)): ?>
    <div class="browse-controls">
        <?= $this->pagination() ?>
        <?= $this->sortSelector($sortHeadings) ?>
    </div>
    <?php $this->trigger('view.browse.before'); ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?= $escape($translate('User')) ?></th>
                <th><?= $escape($translate('Resource')) ?></th>
                <th><?= $escape($translate('Enabled')) ?></th>
                <th>&nbsp;</th>
                <th><?= $escape($translate('Created')) ?></th>
                <th><?= $escape($translate('Modified')) ?></th>
                <th><?= $escape($translate('Token')) ?></th>
                <th><?= $escape($translate('Temporal')) ?></th>
                <th><?= $escape($translate('Start date')) ?></th>
                <th><?= $escape($translate('End date')) ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($accessResources as $accessResource): ?>
            <?php
                if ($user = $accessResource->user()):
                    $userText = $this->hyperlink($user->name(), $user->adminUrl());
                else:
                    $userText = $translate('[no user]');
                endif;

                $resourceType = '';
                $resourceText = '';
                if ($requestedResource = $accessResource->resource()):
                    $resourceType = $requestedResource->resourceName();
                    $resourceText = $requestedResource->linkPretty();
                endif;
            ?>
            <tr>
                <td><?= $userText; ?></td>
                <td class="resource <?= $resourceType; ?>"><?= $resourceText ?></td>
                <td><?= $accessResource->enabled() ? $escape('Yes') : $escape('No') ?></td>
                <td>
                    <ul class="actions">
                        <?php if ($accessResource->userIsAllowed('update')): ?>
                        <li>
                            <?= $this->hyperlink('', $accessResource->url('edit'), [
                                'class' => 'o-icon-edit',
                                'title' => $translate('Edit'),
                            ]) ?>
                        </li>
                        <?php endif; ?>
                        <?php if ($accessResource->userIsAllowed('delete')): ?>
                        <li>
                            <?= $this->hyperlink('', '#', [
                                'data-sidebar-selector' => '#sidebar',
                                'data-sidebar-content-url' => $accessResource->url('delete-confirm'),
                                'class' => 'o-icon-delete sidebar-content',
                                'title' => $translate('Delete'),
                            ]) ?>
                        </li>
                        <?php endif; ?>
                    </ul>
                </td>
                <td><?= $accessResource->created()->format('Y-m-d H:i:s') ?></td>
                <td><?= $accessResource->modified()->format('Y-m-d H:i:s') ?></td>
                <td><?= $accessResource->token() ?></td>
                <td><?= $accessResource->temporal() ? $translate('Yes') : $translate('No') ?></td>
                <td><?= $accessResource->startDate() ? $accessResource->startDate()->format('Y-m-d H:i') : '' ?></td>
                <td><?= $accessResource->endDate() ? $accessResource->endDate()->format('Y-m-d H:i'): '' ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php $this->trigger('view.browse.after'); ?>
    <div class="browse-controls">
        <?= $this->pagination() ?>
    </div>

    <div id="sidebar" class="sidebar">
        <?= $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]) ?>
        <div class="sidebar-content"></div>
    </div>
    <div id="sidebar-delete-selected" class="sidebar">
        <?= $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]) ?>
        <div class="sidebar-content">
            <div id="sidebar-confirm">
                <h3><?= $translate('Delete records') ?></h3>
                <p><?= $translate('Are you sure you would like to delete the selected records?') ?></p>
                <p class="error"><?= sprintf(
                        $translate('%s: this action will permanently delete %s records and cannot be undone.'),
                        sprintf('<strong>%s</strong>', $translate('Warning')),
                        '<strong><span id="delete-selected-count"></span></strong>'
                    ) ?></p>
                <?= 'formDeleteSelected' /*$this->form($this->formDeleteSelected)*/ ?>
            </div>
        </div>
    </div>
    <div id="sidebar-delete-all" class="sidebar">
        <?= $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]) ?>
        <div class="sidebar-content">
            <div id="sidebar-confirm">
                <h3><?= $translate('Delete records') ?></h3>
                <p><?= $translate('Are you sure you would like to delete all records on all pages of this result?') ?></p>
                <p class="error"><?= sprintf(
                        $translate('%s: this action will permanently delete %s records and cannot be undone.'),
                        sprintf('<strong>%s</strong>', $translate('Warning')),
                        sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
                    ) ?></p>
                <label><input type="checkbox" name="confirm-delete-all-check"> <?= $translate('Are you sure?') ?></label>
                <?= 'formDeleteAll' /*$this->form($this->formDeleteAll)*/ ?>
            </div>
        </div>
    </div>

    <script>
        // Complete the batch delete form after confirmation.
        $('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
            var confirmForm = $(this);
            if ('confirm-delete-all' === this.id) {
                confirmForm.append($('.batch-query').clone());
            } else {
                $('#batch-form').find('input[name="resource_ids[]"]:checked').each(function() {
                    confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
                });
            }
        });
        $('.delete-all').on('click', function(e) {
            Omeka.closeSidebar($('#sidebar-delete-selected'));
        });
        $('.delete-selected').on('click', function(e) {
            Omeka.closeSidebar($('#sidebar-delete-all'));
            var inputs = $('input[name="resource_ids[]"]');
            $('#delete-selected-count').text(inputs.filter(':checked').length);
        });
        $('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
            $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
        });
    </script>

<?php else: ?>
    <p><?= $escape($translate('No access records yet.')); ?> <a href="<?= $urlHelper(null, [], true); ?>"><?= $escape($translate('Refresh page')) ?></a></p>
<?php endif; ?>
