<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\DataType\Resource\AbstractResource $dataType
 * @var \AccessResource\Api\Representation\AccessResourceRepresentation $accessResource
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $requestedResource
 * @var \AccessResource\Form\Admin\AccessResourceForm $form
 */

$translate = $this->plugin('translate');
$urlHelper = $this->plugin('url');

$this->headScript()
    ->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($this->assetUrl('js/user-selector.js', 'AccessResource'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'edit items');

$deleteButton = ($accessResource && $accessResource->userIsAllowed('delete'))
    ? '<a href="javascript: void(0)" class="delete button">' . $translate('Delete') . '</a>'
    : null;

$mediaContentUrlOptions = ['query' => []];
if ($requestedResource && $requestedResource instanceof \Omeka\Api\Representation\ItemRepresentation):
    $mediaContentUrlOptions['query']['item_id'] = $requestedResource->id();
endif;

$user = $accessResource ? $accessResource->user() : null;
?>

<?php
if ($accessResource):
        echo $this->pageTitle(sprintf($translate('Access #%d'), $accessResource->id()), 1, $translate('Access resources'), $translate('Edit'));
    else:
        echo $this->pageTitle($translate('New access'), 1, $translate('Access resources'), $translate('Add'));
    endif;
?>
<div id="page-actions">
    <?php
    echo $deleteButton;
    echo $this->hyperlink(
        $translate('Cancel'),
        $urlHelper('admin/access-resource/default', ['controller' => 'access', 'action' => 'browse']),
        ['class' => 'button']
    );
    ?>
</div>

<?php $this->trigger('view.edit.before'); ?>
<?= $this->form()->openTag($form) ?>
    <div class="resource-values field">
        <div class="field-meta">
            <div class="field-label"><?= $translate('Resource') ?></div>
        </div>
        <div class="inputs">
            <div class="values">
                <div class="value value-resource" data-data-type="resource" data-name-prefix="resource">
                    <div class="input-body">
                        <span class="default"><?= $translate('No resource selected') ?></span>
                        <p class="selected-resource">
                            <span class="o-title"></span>
                            <input type="hidden" class="value to-require" data-value-key="value_resource_id" value="<?php $requestedResource ? $requestedResource->id() : null; ?>">
                        </p>
                        <?php
                            echo $this->hyperlink($translate('Item'), '#item-resource-select', [
                                'class' => 'o-icon-items button resource-select',
                                'data-sidebar-content-url' => $urlHelper('admin/default', ['controller' => 'item', 'action' => 'sidebar-select'], false),
                            ]);

                            echo $this->hyperlink($translate('Item set'), '#itemset-resource-select', [
                                'class' => 'o-icon-item-sets button resource-select',
                                'data-sidebar-content-url' => $urlHelper('admin/default', ['controller' => 'item-set', 'action' => 'sidebar-select'], false),
                            ]);

                            echo $this->hyperlink($translate('Media'), '#media-resource-select', [
                                'class' => 'o-icon-media button resource-select',
                                'data-sidebar-content-url' => $urlHelper('admin/default', ['controller' => 'media', 'action' => 'sidebar-select'], $mediaContentUrlOptions, false),
                            ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="resource-values field">
        <div class="field-meta">
            <div class="field-label"><?= $translate('User') ?></div>
        </div>
        <div class="inputs">
            <input type="hidden" name="user_id" value="<?= $user ? $user->id() : '' ?>">
            <div class="selected-user">
                <?php
                    if ($user) {
                        echo $this->hyperlink($user->name(), $user->adminUrl(), ['target' => '_blank']);
                    }
                ?>
            </div>
            <button id="user-selector-button"><?= $user ? $translate('Change user') : $translate('Select user') ?></button>
            <?= $this->userSelector($translate('Click on a user to select it.'), false) ?>
        </div>
    </div>

<?php
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
?>

<?= ($accessResource) ? $this->deleteConfirm($accessResource, 'accessResource') : '' ?>
<?= $this->partial('common/resource-select-sidebar') ?>

<?php $this->trigger('view.edit.after'); ?>

<script>
    $(document).ready(function() {
        var value = $('form .value-resource');
        var valueObj = <?= $requestedResource ? json_encode($requestedResource->valueRepresentation()) : '{}' ?>;
        var namePrefix = value.data('name-prefix');
        $(document).trigger('o:prepare-value', ['resource', value, valueObj, namePrefix]);
    });
</script>
