<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AccessResource\Api\Representation\AccessRequestRepresentation[] $accessRequests
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');

$this->headLink()->appendStylesheet($assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headScript()->appendFile($assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'sites browse');
?>

<?= $this->pageTitle($translate('Resource access dashboard')) ?>

<?php if (count($accessRequests)): ?>
    <div class="browse-controls">

        <?= $this->pagination() ?>
    </div>
    <?php $this->trigger('view.browse.before'); ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <th><?= $escape($translate('Resource')) ?></th>
            <th><?= $escape($translate('Status')) ?></th>
            <th><?= $escape($translate('Created')) ?></th>
            <th><?= $escape($translate('Modified')) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($accessRequests as $accessRequest): ?>
            <?php

            $resourceType = '';
            $resourceText = '';
            if ($requestedResource = $accessRequest->resource()):
                $resourceType = $requestedResource->resourceName();
                $resourceText = $requestedResource->linkPretty();
            endif;
            ?>
            <tr>
                <td class="resource <?= $resourceType; ?>"><?= $resourceText ?></td>
                <td><?= $translate($accessRequest->statusLabel()) ?></td>
                <td><?= $accessRequest->created()->format('Y-m-d H:i:s') ?></td>
                <td><?= $accessRequest->modified() ? $accessRequest->modified()->format('Y-m-d H:i:s') : '' ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
    <p><?= $escape($translate('No request records yet.')) ?> <a href=""><?= $escape($translate('Refresh page')) ?></a></p>
<?php endif; ?>
