<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \AccessResource\Api\Representation\AccessRequestRepresentation[] $accessRequests
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->headLink()->appendStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'));

$this->htmlElement('body')->appendAttribute('class', 'sites browse');
?>

<?php echo $this->pageTitle($translate('Resource access dashboard')); ?>

<?php if (count($accessRequests)): ?>
    <div class="browse-controls">

        <?php echo $this->pagination(); ?>
    </div>
    <?php $this->trigger('view.browse.before'); ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <th><?php echo $escape($translate('Resource')); ?></th>
            <th><?php echo $escape($translate('Status')); ?></th>
            <th><?php echo $escape($translate('Created')); ?></th>
            <th><?php echo $escape($translate('Modified')); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($accessRequests as $accessRequest): ?>
            <?php

            $resourceType = '';
            $resourceText = '';
            if ($requestedResource = $accessRequest->resource()):
                $resourceType = $requestedResource->resourceName();
                $resourceText = $requestedResource->linkPretty();
            endif;
            ?>
            <tr>
                <td class="resource <?php echo $resourceType; ?>"><?php echo $resourceText; ?></td>
                <td><?php echo $translate($accessRequest->statusLabel()); ?></td>
                <td><?php echo $accessRequest->created()->format('Y-m-d H:i:s'); ?></td>
                <td><?php echo $accessRequest->modified()->format('Y-m-d H:i:s'); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
    <p><?php echo $escape($translate('No request records yet.')); ?> <a href=""><?php echo $escape($translate('Refresh page')); ?></a></p>
<?php endif; ?>
